# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check Output Parameters
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"

    - name: Install PowerShell modules
      if: success()
      shell: pwsh
      run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module ModuleBuilder -ErrorAction Stop
            Install-Module MSAL.PS -ErrorAction Stop

    - name: Publish with PowerShell
      env:
        NUGET_KEY: ${{ secrets.PSGALLERYAPIKEY }}
        Version: ${{ github.ref }}
      run: |
        ./Build.ps1 -Version $ENV:Version -APIKey $ENV:NUGET_KEY -Publish
